<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="Vugen" productVer="12" os="" host="PRQAR6"><DocLocation><![CDATA[C:\Users\yojana.joshi\AppData\Local\Temp\2\TD_80\12.53.0.0_952\072396fe\Test\67\67\67]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[67]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="8/7/2018 - 0:31:56" eTime="8/7/2018 - 0:31:56" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Navigate to http://orchidperf103.per...nwidebridge.com/ was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:31:58]]></Time>
<TimeTick>1533616318</TimeTick>
<NodeArgs eType="General" icon="0" nRep="9" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on E mail * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:31:59]]></Time>
<TimeTick>1533616319</TimeTick>
<NodeArgs eType="General" icon="0" nRep="10" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Type perfuser1@oceanwide.com in E mail * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:00]]></Time>
<TimeTick>1533616320</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Type ************** in Password * passwordbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:01]]></Time>
<TimeTick>1533616321</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Press Enter key on Password * passwordbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:03]]></Time>
<TimeTick>1533616323</TimeTick>
<NodeArgs eType="General" icon="0" nRep="13" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on Quotes & Policies  was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:04]]></Time>
<TimeTick>1533616324</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Click on Create New Quote link was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:06]]></Time>
<TimeTick>1533616326</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on File Not Available image was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:11]]></Time>
<TimeTick>1533616331</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Click on 1 Source Insurance Agency,... link was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:14]]></Time>
<TimeTick>1533616334</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[18: Click on #37 test link was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:22]]></Time>
<TimeTick>1533616342</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[20: Click on link (1) image was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:23]]></Time>
<TimeTick>1533616343</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Mouse Over]]></Obj>
<Details plainTxt="False" ><![CDATA[21: Move mouse over September, 2016SuMoTuWeT...2345678Today:...  was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:24]]></Time>
<TimeTick>1533616344</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Mouse Over]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Set Day]]></Obj>
<Details plainTxt="False" ><![CDATA[22: Set Effective Date * datepicker to 30 was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:25]]></Time>
<TimeTick>1533616345</TimeTick>
<NodeArgs eType="General" icon="0" nRep="21" status="Passed" >
<Disp><![CDATA[Set Day]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[24: Select Yes from YesYesNoNo radiogroup was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:25]]></Time>
<TimeTick>1533616345</TimeTick>
<NodeArgs eType="General" icon="0" nRep="22" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[27: Click on Please Select textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:26]]></Time>
<TimeTick>1533616346</TimeTick>
<NodeArgs eType="General" icon="0" nRep="23" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[28: Type Computer  in Please Select textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:27]]></Time>
<TimeTick>1533616347</TimeTick>
<NodeArgs eType="General" icon="0" nRep="24" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[30: Select 11160 Computer Stores from Please Select autocomplete was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:28]]></Time>
<TimeTick>1533616348</TimeTick>
<NodeArgs eType="General" icon="0" nRep="25" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[33: Select Business Owner Policy from BOPBusiness Owner Policy...pertyMonoline... radiogroup was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:28]]></Time>
<TimeTick>1533616348</TimeTick>
<NodeArgs eType="General" icon="0" nRep="26" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[37: Click on Save button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:32]]></Time>
<TimeTick>1533616352</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[39: Click on > button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:35]]></Time>
<TimeTick>1533616355</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[42: Click on Please Select textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:36]]></Time>
<TimeTick>1533616356</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[44: Select option #1 from Please Select listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:57]]></Time>
<TimeTick>1533616377</TimeTick>
<NodeArgs eType="General" icon="0" nRep="30" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[47: Click on Years in Business * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:57]]></Time>
<TimeTick>1533616377</TimeTick>
<NodeArgs eType="General" icon="0" nRep="31" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[48: Type 5 in Years in Business * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:58]]></Time>
<TimeTick>1533616378</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[50: Select Owner from radiogroup (1) radiogroup was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:32:59]]></Time>
<TimeTick>1533616379</TimeTick>
<NodeArgs eType="General" icon="0" nRep="33" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[53: Click on Save button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:02]]></Time>
<TimeTick>1533616382</TimeTick>
<NodeArgs eType="General" icon="0" nRep="34" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[56: Click on > button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:05]]></Time>
<TimeTick>1533616385</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[58: Click on Add button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:07]]></Time>
<TimeTick>1533616387</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[60: Select Yes from YesYesNoNo radiogroup was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:10]]></Time>
<TimeTick>1533616390</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[63: Click on Save & Close button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:13]]></Time>
<TimeTick>1533616393</TimeTick>
<NodeArgs eType="General" icon="0" nRep="38" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[66: Click on Save button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:16]]></Time>
<TimeTick>1533616396</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[68: Click on > button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:20]]></Time>
<TimeTick>1533616400</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[71: Click on Add button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:24]]></Time>
<TimeTick>1533616404</TimeTick>
<NodeArgs eType="General" icon="0" nRep="41" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[72: Wait for Building Information  was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:26]]></Time>
<TimeTick>1533616406</TimeTick>
<NodeArgs eType="General" icon="0" nRep="42" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[73: Click on Please Select textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:27]]></Time>
<TimeTick>1533616407</TimeTick>
<NodeArgs eType="General" icon="0" nRep="43" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[75: Click on 1 gridcell was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:27]]></Time>
<TimeTick>1533616407</TimeTick>
<NodeArgs eType="General" icon="0" nRep="44" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[77: Click on Building # * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:28]]></Time>
<TimeTick>1533616408</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[78: Type 1 in Building # * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:29]]></Time>
<TimeTick>1533616409</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[79: Click on Building Limit textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:30]]></Time>
<TimeTick>1533616410</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[80: Type 1000000 in Building Limit textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:31]]></Time>
<TimeTick>1533616411</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[81: Click on BPP Limit textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:32]]></Time>
<TimeTick>1533616412</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[82: Type 50000 in BPP Limit textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:32]]></Time>
<TimeTick>1533616412</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[84: Click on BI Limit textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:33]]></Time>
<TimeTick>1533616413</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[85: Type 50000 in BI Limit textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:34]]></Time>
<TimeTick>1533616414</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[87: Select 1/3 from BI Limit of Indemnity listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:35]]></Time>
<TimeTick>1533616415</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[89: Select $1,000 from AOP Deductible * listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:35]]></Time>
<TimeTick>1533616415</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Mouse Over]]></Obj>
<Details plainTxt="False" ><![CDATA[90.3: Move mouse over Please Select   select gridcell was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:36]]></Time>
<TimeTick>1533616416</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Mouse Over]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[99: Select 1 from Protection Class listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:37]]></Time>
<TimeTick>1533616417</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[101: Click on Year Built textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:38]]></Time>
<TimeTick>1533616418</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[102: Type 2010 in Year Built textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:38]]></Time>
<TimeTick>1533616418</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[104: Select Fire-Resistive from Construction Type * listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:39]]></Time>
<TimeTick>1533616419</TimeTick>
<NodeArgs eType="General" icon="0" nRep="59" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[106: Click on Sq. Feet * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:40]]></Time>
<TimeTick>1533616420</TimeTick>
<NodeArgs eType="General" icon="0" nRep="60" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[107: Type 100000 in Sq. Feet * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:41]]></Time>
<TimeTick>1533616421</TimeTick>
<NodeArgs eType="General" icon="0" nRep="61" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[109: Click on # of Stories * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:41]]></Time>
<TimeTick>1533616421</TimeTick>
<NodeArgs eType="General" icon="0" nRep="62" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[110: Click on # of Stories * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:42]]></Time>
<TimeTick>1533616422</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[111: Type 2 in # of Stories * textbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:43]]></Time>
<TimeTick>1533616423</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[113: Select Concrete fill from Roofing Covering Type * listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:44]]></Time>
<TimeTick>1533616424</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[117: Select Gable (high pitch) roof ...2 (26.5 degrees) from Roof Shape * listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:44]]></Time>
<TimeTick>1533616424</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[120: Select Less Than 1000 Feet from Distance to Coast * listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:45]]></Time>
<TimeTick>1533616425</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[127: Select 2% from Hurricane/Named Storm... listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:46]]></Time>
<TimeTick>1533616426</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[129: Click on Central Station Fire Alarm radiogroup was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:46]]></Time>
<TimeTick>1533616426</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[139: Select Occurrence from OccurrenceOccurrenceCale...rYearCalendar... radiogroup was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:47]]></Time>
<TimeTick>1533616427</TimeTick>
<NodeArgs eType="General" icon="0" nRep="70" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[142: Click on Save & Close button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:51]]></Time>
<TimeTick>1533616431</TimeTick>
<NodeArgs eType="General" icon="0" nRep="71" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[148: Click on Save button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:55]]></Time>
<TimeTick>1533616435</TimeTick>
<NodeArgs eType="General" icon="0" nRep="72" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[151: Click on > button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:58]]></Time>
<TimeTick>1533616438</TimeTick>
<NodeArgs eType="General" icon="0" nRep="73" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[152: Click on Please Select gridcell was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:59]]></Time>
<TimeTick>1533616439</TimeTick>
<NodeArgs eType="General" icon="0" nRep="74" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[155: Select $1 000 000 from Please Select listbox was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:33:59]]></Time>
<TimeTick>1533616439</TimeTick>
<NodeArgs eType="General" icon="0" nRep="75" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[158: Click on Add button was finished]]></Details>
<Time><![CDATA[8/7/2018 - 0:34:00]]></Time>
<TimeTick>1533616440</TimeTick>
<NodeArgs eType="General" icon="0" nRep="76" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>